// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6wdk6MxdPlKFrkCM7Zr7jH2tEZXqRg0',
    appId: '1:836429824156:android:b29c5c6b67fffccc9ded59',
    messagingSenderId: '836429824156',
    projectId: 'mynotes-fluttertut',
    storageBucket: 'mynotes-fluttertut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-u8iX1rq6GQf7XDHrlWO86s0keCvlHWQ',
    appId: '1:836429824156:ios:18ba42060e26d2109ded59',
    messagingSenderId: '836429824156',
    projectId: 'mynotes-fluttertut',
    storageBucket: 'mynotes-fluttertut.appspot.com',
    iosClientId: '836429824156-6eg4j3jfsjs0enlv0uj5rv66bib9cclk.apps.googleusercontent.com',
    iosBundleId: 'com.denis.mynotes',
  );
}
